import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { Manrope } from 'next/font/google'

const manrope = Manrope({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: "Opal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={`${manrope.className} bg-[#171717]`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
      </ClerkProvider>
    </>
  );
}
